### PR TITLE
Fix: typo by removing 'n' in section 90.1 of TUTORIAL.md

### PR DESCRIPTION
**Pull request by srkds**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/44731

fixed typo by removing 'n' from statement '...questionnaire.sh....'

### CODE REVIEW

**Comment by srkds** [comment]
#44731
[issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/44731)

**Comment by ieahleen** [comment]
I am curious why all the `\r` added... @moT01 what do you say?

**Comment by gikf** [comment]
There are two factors to that:
- Git replaces line endings to `\r\n` locally on windows, by default. When committing git replaces line ending with just `\n`, so `\r` in the line endings doesn't make it into commits.
- CodeRoad cli generates `tutorial.json` using file with `\r\n`. Which is how `\r\n` make into the generated strings.

I guess it could be tried to force git using just `\n` line ending in the repository, with `.gitattributes` file having:

`* text eol=lf`

**Comment by moT01** [comment]
Thanks for clarifying that @gikf. I don't think they cause any problems, but do you think you can manually remove all those from this PR @srkds?

**Review by moT01 — APPROVED** [review]
LGTM 🎉 Thanks for fixing the @srkds 👍 

I removed all those real quick, it should be good to go

**Comment by srkds** [comment]
Thanks 🎉 @gikf, @ieahleen reviewers, for your time and efforts.

@moT01 Thank you🙌 for rebuilding the JSON file and approving this PR 🚀

**Pull request merged**
