### PR TITLE
fix(curriculum): fixed a typo on line 2249 of TUTORIAL.MD

### PR DESCRIPTION
**Pull request by DylanDevelops**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/47115

I was having some trouble getting code road installed via the mac terminal. I have no idea how to fix this and I was a little confused by the instructions. I fixed this typo. In the guide, it said something about running the command `coderoad build` but I can't run this command as coderoad will not install on my system. If someone can help me out it might make it easier but if I did everything right then perfect.

### CODE REVIEW

**Comment by gikf** [comment]
Hey @DylanDevelops 

unfortunately using CodeRoad cli is required step. The `TUTORIAL.md` file is more a human-readable version, the `.json` file generated by cli does the actual work when tutorial is running.

Were you getting any specific error?

**Comment by DylanDevelops** [comment]
This is what I keep getting. any ideas?
Screen Shot 2022-08-02 at 12 24 24 AM

**Comment by DylanDevelops** [comment]
im just installing it to my default directory when opening the terminal. Do I have to install it to my forked repository or anything like that?

**Comment by gikf** [comment]
All is good now. The version branch (`vX.X.X`) is needed to be present locally, as it's also used by the coderoad cli. This is unrelated to the name of the branch for the PR. You must have figured it out, as generating json went well.

**Review by gikf — APPROVED** [review]
LGTM :+1: 

Thanks for fixing the another typo as well.

**Pull request merged**
