### PR TITLE
Issue #44731 of Typo in Lesson 10 in Learn Bash Scripting by Building…

### PR DESCRIPTION
**Pull request by akshat-o5**
… Five Programs is solved

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/44731

### CODE REVIEW

**Review by gikf — CHANGES_REQUESTED** [review]
This tutorial is using CodeRoad VS Code extension, specific guidelines how to contribute to them can be found on https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad. Making PR for this issue will require following parts referring to making changes on the `main` branch.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by akshat-o5** [comment]
Okay, I will rectify it.

**Comment by akshat-o5** [comment]
I had made changes on the main branch. Please refer it.

**Comment by gikf** [comment]
I'm not seeing any new commits here, did you remember to push new changes?

**Comment by akshat-o5** [comment]
I have made the changes in my forked repository. I am a bit confused on how to proceed further, can you please help?

**Comment by akshat-o5** [comment]
I had done , please refer it.

**Comment by akshat-o5** [comment]
I have created another pull reuqest , please see to it.

**Comment by gikf** [comment]
Please follow guidelines I linked before. Further changes should be done on this branch, pushing commit to it will automatically update PR.

**Comment by akshat-o5** [comment]
Due to some error, I am not being able to commit in this PR again. If you close this , I will make a new PR with all the necessary changes required.

**Comment by gikf** [comment]
What error? If you need help contributing join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3), moderators will guide you through this.

**Comment by moT01** [comment]
Thanks for the PR @akshat-o5 - this was fixed with another one so I am going to close it. Happy coding 🎉

**Pull request closed without merging**
